"""v16_schema_strategy_engine

Revision ID: 00082e5f41e5
Revises: ef43c62ca0d6
Create Date: 2026-04-10 21:20:59.101204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00082e5f41e5'
down_revision: Union[str, Sequence[str], None] = 'ef43c62ca0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_missing', sa.Boolean(), nullable=False),
    sa.Column('strategy_hash', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusion_log_date'), 'exclusion_log', ['date'], unique=False)
    op.create_index(op.f('ix_exclusion_log_id'), 'exclusion_log', ['id'], unique=False)
    op.create_index(op.f('ix_exclusion_log_stock_id'), 'exclusion_log', ['stock_id'], unique=False)
    op.create_table('pipeline_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy_hash', sa.String(length=12), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'phase', name='uq_pipeline_date_phase')
    )
    op.create_index(op.f('ix_pipeline_log_date'), 'pipeline_log', ['date'], unique=False)
    op.create_index(op.f('ix_pipeline_log_id'), 'pipeline_log', ['id'], unique=False)
    op.create_table('open_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=True),
    sa.Column('current_stop', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('gain_pct', sa.Float(), nullable=True),
    sa.Column('max_gain_pct', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('gain_phase', sa.String(length=30), nullable=True),
    sa.Column('rs_below_floor_weeks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('partial_exits_taken', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('monster_score', sa.Float(), nullable=True),
    sa.Column('monster_override_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('entry_atr', sa.Float(), nullable=True),
    sa.Column('entry_adv', sa.Float(), nullable=True),
    sa.Column('entry_regime', sa.String(length=20), nullable=True),
    sa.Column('entry_composite_score', sa.Float(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('pattern_type', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('correlation_adj_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('beta_adj_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('thin_float_adj_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('strategy_hash', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('exit_phase', sa.String(length=30), nullable=True),
    sa.Column('exit_rule_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'entry_date', name='uq_openpos_stock_entry')
    )
    op.create_index(op.f('ix_open_positions_id'), 'open_positions', ['id'], unique=False)
    op.create_index(op.f('ix_open_positions_stock_id'), 'open_positions', ['stock_id'], unique=False)
    op.create_table('turnaround_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('eps_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'detected_date', name='uq_turnaround_stock_date')
    )
    op.create_index(op.f('ix_turnaround_watch_id'), 'turnaround_watch', ['id'], unique=False)
    op.create_index(op.f('ix_turnaround_watch_stock_id'), 'turnaround_watch', ['stock_id'], unique=False)
    op.add_column('fundamentals', sa.Column('ocf_cr', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('opm', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('other_income_cr', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('trade_receivables_days', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('strategy_hash', sa.String(length=12), nullable=True))
    op.add_column('stocks', sa.Column('bse_code', sa.String(length=20), nullable=True))
    op.add_column('stocks', sa.Column('pledge_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('sebi_fine_last_24m', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stocks', sa.Column('lodr_fine_last_12m', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stocks', sa.Column('sebi_investigation_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stocks', sa.Column('business_pivot_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('stocks', sa.Column('is_psu', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stocks', sa.Column('beta', sa.Float(), nullable=True))
    # NOTE: skipping watchlist.earnings_date nullable change — false positive
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'beta')
    op.drop_column('stocks', 'is_psu')
    op.drop_column('stocks', 'business_pivot_count')
    op.drop_column('stocks', 'sebi_investigation_active')
    op.drop_column('stocks', 'lodr_fine_last_12m')
    op.drop_column('stocks', 'sebi_fine_last_24m')
    op.drop_column('stocks', 'pledge_pct')
    op.drop_column('stocks', 'bse_code')
    op.drop_column('scores', 'strategy_hash')
    op.drop_column('fundamentals', 'trade_receivables_days')
    op.drop_column('fundamentals', 'other_income_cr')
    op.drop_column('fundamentals', 'opm')
    op.drop_column('fundamentals', 'ocf_cr')
    op.drop_index(op.f('ix_turnaround_watch_stock_id'), table_name='turnaround_watch')
    op.drop_index(op.f('ix_turnaround_watch_id'), table_name='turnaround_watch')
    op.drop_table('turnaround_watch')
    op.drop_index(op.f('ix_open_positions_stock_id'), table_name='open_positions')
    op.drop_index(op.f('ix_open_positions_id'), table_name='open_positions')
    op.drop_table('open_positions')
    op.drop_index(op.f('ix_pipeline_log_id'), table_name='pipeline_log')
    op.drop_index(op.f('ix_pipeline_log_date'), table_name='pipeline_log')
    op.drop_table('pipeline_log')
    op.drop_index(op.f('ix_exclusion_log_stock_id'), table_name='exclusion_log')
    op.drop_index(op.f('ix_exclusion_log_id'), table_name='exclusion_log')
    op.drop_index(op.f('ix_exclusion_log_date'), table_name='exclusion_log')
    op.drop_table('exclusion_log')
    # ### end Alembic commands ###
