"""full_schema_v2

Revision ID: a79a34bbc118
Revises: 3343baaf44f6
Create Date: 2026-03-18 17:32:26.240164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79a34bbc118'
down_revision: Union[str, Sequence[str], None] = '3343baaf44f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('parent_sector', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_data_id'), 'sector_data', ['id'], unique=False)
    op.create_index(op.f('ix_sector_data_sector_name'), 'sector_data', ['sector_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('delivery_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Float(), nullable=True),
    sa.Column('traded_qty', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_delivery_stock_date')
    )
    op.create_index(op.f('ix_delivery_data_date'), 'delivery_data', ['date'], unique=False)
    op.create_index(op.f('ix_delivery_data_id'), 'delivery_data', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_data_stock_id'), 'delivery_data', ['stock_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_yoy_growth', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_yoy_growth', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'quarter', name='uq_fundamentals_stock_quarter')
    )
    op.create_index(op.f('ix_fundamentals_id'), 'fundamentals', ['id'], unique=False)
    op.create_index(op.f('ix_fundamentals_stock_id'), 'fundamentals', ['stock_id'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('ma150', sa.Float(), nullable=True),
    sa.Column('ma200', sa.Float(), nullable=True),
    sa.Column('rs_score', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('low_52w', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_indicators_stock_date')
    )
    op.create_index(op.f('ix_indicators_date'), 'indicators', ['date'], unique=False)
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_stock_id'), 'indicators', ['stock_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kite_order_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_stock_id'), 'orders', ['stock_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('sector_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('accumulation_score', sa.Float(), nullable=True),
    sa.Column('breakout_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_scores_stock_date')
    )
    op.create_index(op.f('ix_scores_date'), 'scores', ['date'], unique=False)
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_scores_stock_id'), 'scores', ['stock_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('stop_loss_level', sa.Float(), nullable=True),
    sa.Column('sector_name', sa.String(length=100), nullable=True),
    sa.Column('sector_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'stock_id', name='uq_watchlist_date_stock')
    )
    op.create_index(op.f('ix_watchlist_date'), 'watchlist', ['date'], unique=False)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_stock_id'), 'watchlist', ['stock_id'], unique=False)
    op.create_foreign_key(None, 'eod_prices', 'stocks', ['stock_id'], ['id'])
    op.add_column('stocks', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('exchange', sa.String(length=10), nullable=False))
    op.add_column('stocks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_stocks_sector_id'), 'stocks', ['sector_id'], unique=False)
    op.create_foreign_key(None, 'stocks', 'sector_data', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_index(op.f('ix_stocks_sector_id'), table_name='stocks')
    op.drop_column('stocks', 'is_active')
    op.drop_column('stocks', 'exchange')
    op.drop_column('stocks', 'market_cap')
    op.drop_column('stocks', 'sector_id')
    op.drop_constraint(None, 'eod_prices', type_='foreignkey')
    op.drop_index(op.f('ix_watchlist_stock_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_date'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_scores_stock_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_date'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stock_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_indicators_stock_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_date'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_fundamentals_stock_id'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_delivery_data_stock_id'), table_name='delivery_data')
    op.drop_index(op.f('ix_delivery_data_id'), table_name='delivery_data')
    op.drop_index(op.f('ix_delivery_data_date'), table_name='delivery_data')
    op.drop_table('delivery_data')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sector_data_sector_name'), table_name='sector_data')
    op.drop_index(op.f('ix_sector_data_id'), table_name='sector_data')
    op.drop_table('sector_data')
    # ### end Alembic commands ###
