"""v7_schema_enhancement

Revision ID: acfe3af29117
Revises: a79a34bbc118
Create Date: 2026-03-19 20:31:06.963514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acfe3af29117'
down_revision: Union[str, Sequence[str], None] = 'a79a34bbc118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.Column('run_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('nifty_alpha', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('expectancy_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_holding_days', sa.Float(), nullable=True),
    sa.Column('annual_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed_gate', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_table('fii_dii_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fii_buy_cr', sa.Float(), nullable=True),
    sa.Column('fii_sell_cr', sa.Float(), nullable=True),
    sa.Column('fii_net_cr', sa.Float(), nullable=True),
    sa.Column('dii_buy_cr', sa.Float(), nullable=True),
    sa.Column('dii_sell_cr', sa.Float(), nullable=True),
    sa.Column('dii_net_cr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fii_dii_data_date'), 'fii_dii_data', ['date'], unique=True)
    op.create_index(op.f('ix_fii_dii_data_id'), 'fii_dii_data', ['id'], unique=False)
    op.create_table('walkforward_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_type', sa.String(length=20), nullable=False),
    sa.Column('fold', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('is_sharpe', sa.Float(), nullable=True),
    sa.Column('oos_sharpe', sa.Float(), nullable=True),
    sa.Column('oos_is_ratio', sa.Float(), nullable=True),
    sa.Column('is_cagr', sa.Float(), nullable=True),
    sa.Column('oos_cagr', sa.Float(), nullable=True),
    sa.Column('passed_gate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walkforward_results_id'), 'walkforward_results', ['id'], unique=False)
    op.create_table('bulk_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('deal_type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_institution', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_deals_date'), 'bulk_deals', ['date'], unique=False)
    op.create_index(op.f('ix_bulk_deals_id'), 'bulk_deals', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_deals_stock_id'), 'bulk_deals', ['stock_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('ratio_from', sa.Integer(), nullable=True),
    sa.Column('ratio_to', sa.Integer(), nullable=True),
    sa.Column('adj_factor', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'ex_date', 'action_type', name='uq_corpaction_stock_date_type')
    )
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_id'), 'corporate_actions', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_stock_id'), 'corporate_actions', ['stock_id'], unique=False)
    op.create_table('performance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('actual_fill', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('pnl_inr', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('max_gain_pct', sa.Float(), nullable=True),
    sa.Column('max_loss_pct', sa.Float(), nullable=True),
    sa.Column('pattern_type', sa.String(length=20), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=20), nullable=True),
    sa.Column('vol_scalar_at_entry', sa.Float(), nullable=True),
    sa.Column('obv_bonus_at_entry', sa.Integer(), nullable=True),
    sa.Column('earnings_flagged', sa.Boolean(), nullable=True),
    sa.Column('days_to_earnings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_log_id'), 'performance_log', ['id'], unique=False)
    op.create_index(op.f('ix_performance_log_stock_id'), 'performance_log', ['stock_id'], unique=False)
    op.create_table('shareholding_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quarter_end_date', sa.Date(), nullable=False),
    sa.Column('promoter_pct', sa.Float(), nullable=True),
    sa.Column('fii_pct', sa.Float(), nullable=True),
    sa.Column('dii_pct', sa.Float(), nullable=True),
    sa.Column('public_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'quarter_end_date', name='uq_shareholding_stock_quarter')
    )
    op.create_index(op.f('ix_shareholding_pattern_id'), 'shareholding_pattern', ['id'], unique=False)
    op.create_index(op.f('ix_shareholding_pattern_stock_id'), 'shareholding_pattern', ['stock_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pivot_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('obv_slope', sa.Float(), nullable=True),
    sa.Column('obv_bonus', sa.Integer(), nullable=False),
    sa.Column('obv_divergence', sa.Boolean(), nullable=False),
    sa.Column('adl_ratio', sa.Float(), nullable=True),
    sa.Column('inst_flow_signal', sa.String(length=20), nullable=True),
    sa.Column('inst_flow_positive', sa.Boolean(), nullable=True),
    sa.Column('base_length_days', sa.Integer(), nullable=True),
    sa.Column('base_depth_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('crash_warning', sa.Boolean(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('days_to_earnings', sa.Integer(), nullable=True),
    sa.Column('earnings_flag', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('vol_scalar', sa.Float(), nullable=True),
    sa.Column('fundamental_bonus', sa.Integer(), nullable=True),
    sa.Column('confirmed_date', sa.Date(), nullable=True),
    sa.Column('failed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_signal_date'), 'signals', ['signal_date'], unique=False)
    op.create_index(op.f('ix_signals_stock_id'), 'signals', ['stock_id'], unique=False)
    op.add_column('eod_prices', sa.Column('adj_close', sa.Float(), nullable=True))
    op.add_column('eod_prices', sa.Column('adj_factor', sa.Float(), nullable=True))
    op.add_column('eod_prices', sa.Column('traded_value_cr', sa.Float(), nullable=True))
    op.add_column('eod_prices', sa.Column('hit_upper_circuit', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('eod_prices', sa.Column('hit_lower_circuit', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('fundamentals', sa.Column('reporting_date', sa.Date(), nullable=True))
    op.add_column('fundamentals', sa.Column('expected_result_date', sa.Date(), nullable=True))
    op.add_column('fundamentals', sa.Column('analyst_revision', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('is_financial', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('indicators', sa.Column('ma200_slope', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('rs_rank', sa.Integer(), nullable=True))
    op.add_column('indicators', sa.Column('mom_3m', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('mom_6m', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('mom_12_1', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('raw_score', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('scaled_score', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('vol_scalar', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('mom_vol_20d', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('mom_quality', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('obv', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('adl_ratio', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('vol_ratio_20', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('vol_ratio_50', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('pct_from_high', sa.Float(), nullable=True))
    op.add_column('indicators', sa.Column('delivery_trend', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('free_float_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('avg_daily_tv_cr', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('is_asm', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('is_esm', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('is_financial', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('is_fii_capped_sector', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('promoter_holding_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('fii_holding_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('dii_holding_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('fii_headroom_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('is_fii_breached', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('is_fii_cautioned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stocks', sa.Column('shareholding_date', sa.Date(), nullable=True))
    op.add_column('stocks', sa.Column('listing_date', sa.Date(), nullable=True))
    op.add_column('stocks', sa.Column('delisted_date', sa.Date(), nullable=True))
    op.add_column('watchlist', sa.Column('tier', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('momentum_score', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('fundamental_bonus', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('obv_bonus', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('adl_ratio', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('delivery_trend', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('inst_flow_signal', sa.String(length=20), nullable=True))
    op.add_column('watchlist', sa.Column('inst_flow_positive', sa.Boolean(), nullable=True))
    op.add_column('watchlist', sa.Column('entry_zone_low', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('entry_zone_high', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('suggested_size_pct', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('vol_scalar', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('earnings_date', sa.Date(), nullable=True))
    op.add_column('watchlist', sa.Column('earnings_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'earnings_flag')
    op.drop_column('watchlist', 'earnings_date')
    op.drop_column('watchlist', 'vol_scalar')
    op.drop_column('watchlist', 'suggested_size_pct')
    op.drop_column('watchlist', 'entry_zone_high')
    op.drop_column('watchlist', 'entry_zone_low')
    op.drop_column('watchlist', 'inst_flow_positive')
    op.drop_column('watchlist', 'inst_flow_signal')
    op.drop_column('watchlist', 'delivery_trend')
    op.drop_column('watchlist', 'adl_ratio')
    op.drop_column('watchlist', 'obv_bonus')
    op.drop_column('watchlist', 'fundamental_bonus')
    op.drop_column('watchlist', 'momentum_score')
    op.drop_column('watchlist', 'signal_id')
    op.drop_column('watchlist', 'tier')
    op.drop_column('stocks', 'delisted_date')
    op.drop_column('stocks', 'listing_date')
    op.drop_column('stocks', 'shareholding_date')
    op.drop_column('stocks', 'is_fii_cautioned')
    op.drop_column('stocks', 'is_fii_breached')
    op.drop_column('stocks', 'fii_headroom_pct')
    op.drop_column('stocks', 'dii_holding_pct')
    op.drop_column('stocks', 'fii_holding_pct')
    op.drop_column('stocks', 'promoter_holding_pct')
    op.drop_column('stocks', 'is_fii_capped_sector')
    op.drop_column('stocks', 'is_financial')
    op.drop_column('stocks', 'is_esm')
    op.drop_column('stocks', 'is_asm')
    op.drop_column('stocks', 'avg_daily_tv_cr')
    op.drop_column('stocks', 'free_float_pct')
    op.drop_column('indicators', 'delivery_trend')
    op.drop_column('indicators', 'pct_from_high')
    op.drop_column('indicators', 'vol_ratio_50')
    op.drop_column('indicators', 'vol_ratio_20')
    op.drop_column('indicators', 'adl_ratio')
    op.drop_column('indicators', 'obv')
    op.drop_column('indicators', 'mom_quality')
    op.drop_column('indicators', 'mom_vol_20d')
    op.drop_column('indicators', 'vol_scalar')
    op.drop_column('indicators', 'scaled_score')
    op.drop_column('indicators', 'raw_score')
    op.drop_column('indicators', 'mom_12_1')
    op.drop_column('indicators', 'mom_6m')
    op.drop_column('indicators', 'mom_3m')
    op.drop_column('indicators', 'rs_rank')
    op.drop_column('indicators', 'ma200_slope')
    op.drop_column('fundamentals', 'is_financial')
    op.drop_column('fundamentals', 'analyst_revision')
    op.drop_column('fundamentals', 'expected_result_date')
    op.drop_column('fundamentals', 'reporting_date')
    op.drop_column('eod_prices', 'hit_lower_circuit')
    op.drop_column('eod_prices', 'hit_upper_circuit')
    op.drop_column('eod_prices', 'traded_value_cr')
    op.drop_column('eod_prices', 'adj_factor')
    op.drop_column('eod_prices', 'adj_close')
    op.drop_index(op.f('ix_signals_stock_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_date'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_shareholding_pattern_stock_id'), table_name='shareholding_pattern')
    op.drop_index(op.f('ix_shareholding_pattern_id'), table_name='shareholding_pattern')
    op.drop_table('shareholding_pattern')
    op.drop_index(op.f('ix_performance_log_stock_id'), table_name='performance_log')
    op.drop_index(op.f('ix_performance_log_id'), table_name='performance_log')
    op.drop_table('performance_log')
    op.drop_index(op.f('ix_corporate_actions_stock_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_bulk_deals_stock_id'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_id'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_date'), table_name='bulk_deals')
    op.drop_table('bulk_deals')
    op.drop_index(op.f('ix_walkforward_results_id'), table_name='walkforward_results')
    op.drop_table('walkforward_results')
    op.drop_index(op.f('ix_fii_dii_data_id'), table_name='fii_dii_data')
    op.drop_index(op.f('ix_fii_dii_data_date'), table_name='fii_dii_data')
    op.drop_table('fii_dii_data')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
