"""add_market_regime_log

Revision ID: da78da0319f6
Revises: 00082e5f41e5
Create Date: 2026-04-11 07:10:22.046139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da78da0319f6'
down_revision: Union[str, Sequence[str], None] = '00082e5f41e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regime_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('crash_warning', sa.Boolean(), nullable=False),
    sa.Column('fast_crash_active', sa.Boolean(), nullable=False),
    sa.Column('strategy_hash', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_regime_log_date')
    )
    op.create_index(op.f('ix_market_regime_log_date'), 'market_regime_log', ['date'], unique=False)
    op.create_index(op.f('ix_market_regime_log_id'), 'market_regime_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_regime_log_id'), table_name='market_regime_log')
    op.drop_index(op.f('ix_market_regime_log_date'), table_name='market_regime_log')
    op.drop_table('market_regime_log')
    # ### end Alembic commands ###
