"""add_screener_export_id

Revision ID: ef43c62ca0d6
Revises: acfe3af29117
Create Date: 2026-03-19 20:56:50.189040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef43c62ca0d6'
down_revision: Union[str, Sequence[str], None] = 'acfe3af29117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('screener_export_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'screener_export_id')
    # ### end Alembic commands ###
