"""Email notifications via Resend API."""
import resend
from datetime import date
from loguru import logger
from sqlalchemy import text
from sqlalchemy.orm import Session
from momentum_edge.config import settings


def _init_resend():
    if not settings.resend_api_key:
        logger.warning("RESEND_API_KEY not set — email disabled")
        return False
    resend.api_key = settings.resend_api_key
    return True


def send_daily_digest(db: Session, target_date: date) -> bool:
    """
    Send daily watchlist digest email.
    Queries watchlist + scores for the date and formats an HTML email.
    """
    if not _init_resend():
        return False

    # Query watchlist
    rows = db.execute(text("""
        SELECT w.rank, s.symbol, w.composite_score, w.pattern_type,
               w.regime, w.stop_loss_level, w.sector_name
        FROM watchlist w JOIN stocks s ON s.id = w.stock_id
        WHERE w.date = :d ORDER BY w.rank
    """), {"d": target_date}).fetchall()

    if not rows:
        logger.info("No watchlist for digest")
        return False

    regime = rows[0][4] or "Unknown"

    # Build HTML table
    table_rows = ""
    for r in rows:
        table_rows += f"<tr><td>{r[0]}</td><td><b>{r[1]}</b></td><td>{r[2]:.1f}</td><td>{r[3] or '—'}</td><td>{r[5]:.2f if r[5] else '—'}</td><td>{r[6] or '—'}</td></tr>"

    html = f"""
    <h2>MomentumEdge Daily Watchlist — {target_date}</h2>
    <p><b>Regime:</b> {regime}</p>
    <table border="1" cellpadding="5" cellspacing="0" style="border-collapse:collapse;">
    <tr style="background:#f0f0f0;"><th>#</th><th>Symbol</th><th>Score</th><th>Pattern</th><th>Stop Loss</th><th>Sector</th></tr>
    {table_rows}
    </table>
    <p style="color:#666;font-size:12px;">Generated by MomentumEdge v7 pipeline</p>
    """

    try:
        resend.Emails.send({
            "from": settings.resend_from_email,
            "to": [settings.alert_email],
            "subject": f"MomentumEdge — {target_date} | {regime} | {len(rows)} stocks",
            "html": html,
        })
        logger.info(f"Daily digest sent to {settings.alert_email}")
        return True
    except Exception as e:
        logger.error(f"Failed to send digest: {e}")
        return False


def send_alert(message: str) -> bool:
    """Send a simple alert email."""
    if not _init_resend():
        return False
    try:
        resend.Emails.send({
            "from": settings.resend_from_email,
            "to": [settings.alert_email],
            "subject": f"MomentumEdge ALERT",
            "html": f"<p>{message}</p>",
        })
        return True
    except Exception as e:
        logger.error(f"Alert send failed: {e}")
        return False
